### ISSUE TITLE
Feature request: open terminal

### ISSUE THREAD

**Issue by josuealcalde** [whaler/whaler#3]
I like your app a lot. 
Simple and clean. Very useful for my team mates.

I think it would be great to have an option to open a terminal for any container.

**Comment by cravler** [comment]
You can run any command inside container by running:

```sh
whaler run <service_name>.[app_name]
```
`container_name` = `<service_name>.[app_name]`

If your app name same as folder name and you in it's root, you can use just `<service_name>.`

For more info see `whaler run --help`
